---
abstract: 'QBit validator'
author:
  - 'Igor Sverdlov <igor-sverdlov@mail.ru>'
build_requires:
  Test::Deep: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.143240'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: QBit-Validator
requires:
  Exception: '0'
  Exporter: '0'
  QBit::Class: '0'
  Scalar::Util: '0'
  base: '0'
  qbit: '0'
version: '0.012'
x_serialization_backend: 'YAML::Tiny version 1.70'
